# Generated by Django 2.2.1 on 2021-09-04 00:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0161_user_subscribed_to_watchtower'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwapRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.CharField(max_length=60)),
                ('to_address', models.CharField(max_length=60)),
                ('token', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receive_transaction_hash', models.CharField(max_length=70)),
                ('date_fulfilled', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps', to='main.User')),
            ],
        ),
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_transaction_hash', models.CharField(max_length=70)),
                ('metadata_transaction_hash', models.CharField(max_length=70)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('swap_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bridge.SwapRequest')),
            ],
        ),
    ]
