# Generated by Django 2.2.1 on 2021-09-04 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slp_token_id', models.CharField(max_length=70)),
                ('slp_source_address', models.CharField(max_length=60)),
                ('slp_balance', models.FloatField(default=0)),
                ('sep20_contract', models.CharField(max_length=60)),
                ('sep20_source_address', models.CharField(max_length=60)),
                ('sep20_balance', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps', to='bridge.Token'),
        ),
    ]
