# Generated by Django 2.2.1 on 2021-09-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0002_auto_20210904_0108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fulfillment',
            old_name='metadata_transaction_hash',
            new_name='slp_burn_transaction_hash',
        ),
        migrations.AddField(
            model_name='token',
            name='burn_slp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='token',
            name='mode',
            field=models.CharField(choices=[('one-way', 'One-Way'), ('two-way', 'Two-Way')], default='two-way', max_length=10),
        ),
        migrations.AddField(
            model_name='token',
            name='sep20_decimals',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='slp_decimals',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='slp_to_sep20_ratio',
            field=models.IntegerField(default=1),
        ),
    ]
