# Generated by Django 2.2.1 on 2021-09-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0003_auto_20210904_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaprequest',
            name='telegram_chat_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
