# Generated by Django 2.2.1 on 2021-10-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0004_swaprequest_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='slp_wallet_xpub',
            field=models.TextField(blank=True),
        ),
    ]
