# Generated by Django 2.2.1 on 2021-10-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0005_token_slp_wallet_xpub'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='sep20_minimum_amount',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='token',
            name='slp_minimum_amount',
            field=models.IntegerField(default=100),
        ),
    ]
