# Generated by Django 2.2.1 on 2021-10-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0006_auto_20211011_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfillment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
