# Generated by Django 2.2.1 on 2021-10-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0007_fulfillment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='slp_wallet_hash',
            field=models.TextField(blank=True),
        ),
    ]
