# Generated by Django 2.2.1 on 2021-10-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0008_token_slp_wallet_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfillment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
