# Generated by Django 2.2.1 on 2021-11-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0009_auto_20211021_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='slp_to_sep20_ratio',
            field=models.FloatField(default=1),
        ),
    ]
