steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/spice-slp-token/spicebot:$REVISION_ID', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/spice-slp-token/spicebot:$REVISION_ID']
