# Generated by Django 2.2.1 on 2019-10-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_auto_20190927_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='anon_name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
