# Generated by Django 2.2.1 on 2019-10-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_auto_20190927_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ban',
            field=models.BooleanField(default=False),
        ),
    ]
