# Generated by Django 2.2.1 on 2019-10-04 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_user_ban'),
        ('main', '0065_user_anon_name'),
    ]

    operations = [
    ]
