# Generated by Django 2.2.1 on 2019-10-05 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_auto_20191004_0958'),
        ('main', '0067_auto_20191002_1401'),
    ]

    operations = [
    ]
