# Generated by Django 2.2.1 on 2019-10-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_merge_20191005_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_username',
            field=models.BooleanField(default=True),
        ),
    ]
