# Generated by Django 2.2.1 on 2019-10-17 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_errorlogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ErrorLogs',
            new_name='ErrorLog',
        ),
    ]
