# Generated by Django 2.2.1 on 2019-10-17 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_weeklyreport'),
        ('main', '0071_auto_20191017_0443'),
    ]

    operations = [
    ]
