# Generated by Django 2.2.1 on 2019-11-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_merge_20191017_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('token', models.CharField(max_length=16, unique=True)),
                ('email', models.CharField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('payment', models.BooleanField(default=False)),
            ],
        ),
    ]
