# Generated by Django 2.2.1 on 2019-11-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_deposit_date_processed'),
    ]

        
    operations = [
        migrations.AddField(
            model_name='deposit',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        )
    ]
