# Generated by Django 2.2.1 on 2019-11-14 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_deposit_custom'),
        ('main', '0073_subscriber'),
    ]

    operations = [
    ]
