# Generated by Django 2.2.1 on 2019-11-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_merge_20191114_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinBlockHeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
    ]
