# Generated by Django 2.2.1 on 2019-11-13 08:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_merge_20191113_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
