# Generated by Django 2.2.1 on 2019-11-14 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_bitcoinblockheight'),
        ('main', '0078_auto_20191113_0812'),
    ]

    operations = [
    ]
