# Generated by Django 2.2.1 on 2019-11-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_auto_20191115_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='app_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
