# Generated by Django 2.2.1 on 2019-11-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_subscriber_app_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='transferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='media',
            name='transferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramgroup',
            name='transferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='transferred',
            field=models.BooleanField(default=False),
        ),
    ]
