# Generated by Django 2.2.1 on 2019-12-31 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_user_seed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='seed',
        ),
    ]
