# Generated by Django 2.2.1 on 2019-12-31 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_remove_user_seed'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='main_transa_transac_c55036_idx'),
        ),
    ]
