# Generated by Django 2.2.1 on 2020-01-27 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_auto_20200124_2219'),
        ('main', '0087_transaction_running_balance'),
    ]

    operations = [
    ]