# Generated by Django 2.2.1 on 2020-01-29 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_merge_20200127_1020'),
        ('main', '0088_merge_20200127_1326'),
    ]

    operations = [
    ]
