# Generated by Django 2.2.1 on 2020-01-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_merge_20200129_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='remark',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
