# Generated by Django 2.2.1 on 2020-03-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_lasttelegrammessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_muted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='muted_count',
        ),
        migrations.AddField(
            model_name='mute',
            name='base_fee',
            field=models.FloatField(default=20000),
        ),
        migrations.AddField(
            model_name='mute',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mute',
            name='is_muted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mute',
            name='next_fee',
            field=models.FloatField(default=0.0),
        ),
    ]
