# Generated by Django 2.2.1 on 2020-03-05 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0094_auto_20200304_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='slp_token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.SLPToken'),
        ),
    ]
