# Generated by Django 2.2.1 on 2020-03-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0095_deposit_slp_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='slptoken',
            name='withdrawal_limit',
            field=models.FloatField(default=1000),
        ),
    ]
