# Generated by Django 2.2.1 on 2020-03-11 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0096_slptoken_withdrawal_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='slp_token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='main.SLPToken'),
        ),
    ]
