# Generated by Django 2.2.1 on 2020-03-12 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0097_withdrawal_slp_token'),
        ('main', '0096_content_slp_token'),
    ]

    operations = [
    ]
