# Generated by Django 2.2.1 on 2020-03-17 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0098_merge_20200312_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mute',
            name='base_fee',
            field=models.FloatField(default=25000),
        ),
        migrations.AlterField(
            model_name='mute',
            name='remaining_fee',
            field=models.FloatField(default=25000),
        ),
    ]
