# Generated by Django 2.2.1 on 2020-03-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_auto_20200317_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='slptoken',
            name='big_deposit_threshold',
            field=models.FloatField(default=50000),
        ),
    ]
