# Generated by Django 2.2.1 on 2020-03-18 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_auto_20200317_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('fee_type', models.CharField(max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fees', to='main.TelegramGroup')),
            ],
        ),
    ]
