# Generated by Django 2.2.1 on 2020-03-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='mute',
            name='remaining_unmute_fee',
            field=models.FloatField(default=0.0),
        ),
    ]
