# Generated by Django 2.2.1 on 2020-03-19 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_slptoken_big_deposit_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='rain',
            name='slp_token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rains', to='main.SLPToken'),
        ),
        migrations.AddField(
            model_name='slptoken',
            name='min_rain_amount',
            field=models.FloatField(default=500),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='slp_token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='main.SLPToken'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='slp_token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='main.SLPToken'),
        ),
    ]
