# Generated by Django 2.2.1 on 2020-03-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0101_mute_remaining_unmute_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='mute',
            name='is_being_unmuted',
            field=models.BooleanField(default=False),
        ),
    ]
