# Generated by Django 2.2.1 on 2020-03-20 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0102_mute_is_being_unmuted'),
        ('main', '0101_auto_20200319_0853'),
    ]

    operations = [
    ]
