# Generated by Django 2.2.1 on 2020-03-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0103_merge_20200320_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='operation',
            field=models.CharField(default='', max_length=50),
        ),
    ]
