# Generated by Django 2.2.1 on 2020-03-24 09:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0104_transaction_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_metrics', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('withdrawal_metrics', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('deposit_metrics', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('tip_metrics', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('rain_metrics', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('game_metrics', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
    ]
