# Generated by Django 2.2.1 on 2020-03-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0106_user_last_private_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='slptoken',
            name='emoji',
            field=models.CharField(default='💰', max_length=10),
        ),
    ]
