# Generated by Django 2.2.1 on 2020-03-26 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0107_slptoken_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='date_recorded',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
