# Generated by Django 2.2.1 on 2020-04-02 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0110_mute_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramgroup',
            old_name='token_tipping_status',
            new_name='settings',
        ),
    ]
