# Generated by Django 2.2.1 on 2020-04-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0111_auto_20200402_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramgroup',
            name='profile_pic_file_id',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='telegramgroup',
            name='profile_pic_url',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
