# Generated by Django 2.2.1 on 2020-04-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0111_auto_20200402_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramgroup',
            name='pillory_fee',
            field=models.FloatField(default=25000),
        ),
        migrations.AddField(
            model_name='telegramgroup',
            name='pillory_time',
            field=models.FloatField(default=720),
        ),
        migrations.DeleteModel(
            name='Fee',
        ),
    ]
