# Generated by Django 2.2.1 on 2020-04-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0112_slptoken_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='mute',
            name='static_duration',
            field=models.FloatField(default=0.0),
        ),
    ]
