# Generated by Django 2.2.1 on 2020-04-15 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0113_mute_static_duration'),
        ('main', '0112_auto_20200414_0730'),
    ]

    operations = [
    ]
