# Generated by Django 2.2.1 on 2020-04-23 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0113_auto_20200423_0254'),
        ('main', '0114_merge_20200415_0852'),
    ]

    operations = [
    ]
