# Generated by Django 2.2.1 on 2020-04-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0114_merge_20200415_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='deposit',
            unique_together={('user', 'transaction_id')},
        ),
    ]
