# Generated by Django 2.2.1 on 2020-04-23 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0115_merge_20200423_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mute',
            name='static_duration',
        ),
    ]
