# Generated by Django 2.2.1 on 2020-04-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0116_remove_mute_static_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='mute',
            name='fee_changed',
            field=models.BooleanField(default=False),
        ),
    ]
