# Generated by Django 2.2.1 on 2020-04-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0117_mute_fee_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='mute',
            name='contributors',
            field=models.ManyToManyField(related_name='mutes_contributed', to='main.User'),
        ),
    ]
