# Generated by Django 2.2.1 on 2020-04-27 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0118_mute_contributors'),
        ('main', '0115_auto_20200424_1015'),
    ]

    operations = [
    ]
