# Generated by Django 2.2.1 on 2020-05-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0121_auto_20200503_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
