# Generated by Django 2.2.1 on 2020-05-05 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0120_auto_20200429_0755'),
        ('main', '0123_auto_20200503_1011'),
    ]

    operations = [
    ]
