# Generated by Django 2.2.1 on 2020-05-12 02:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0125_user_frozen'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='connected_transactions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None),
        ),
    ]
