# Generated by Django 2.2.1 on 2020-05-21 01:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0126_transaction_connected_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='group_metrics',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
