# Generated by Django 2.2.1 on 2020-05-21 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0127_metric_group_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='main.TelegramGroup'),
        ),
    ]
