# Generated by Django 2.2.1 on 2020-07-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0129_slptoken_min_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slpnotified',
            field=models.BooleanField(default=False),
        ),
    ]
