# Generated by Django 2.2.1 on 2020-08-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0130_user_slpnotified'),
    ]

    operations = [
        migrations.AddField(
            model_name='slptoken',
            name='tip_percentage_fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='slptoken',
            name='tip_threshold',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='slptoken',
            name='withdrawal_percentage_fee',
            field=models.FloatField(default=0.0),
        ),
    ]
