# Generated by Django 2.2.1 on 2020-08-20 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0131_auto_20200806_0738'),
        ('main', '0131_auto_20200807_0338'),
    ]

    operations = [
    ]
