# Generated by Django 2.2.1 on 2020-09-27 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0132_merge_20200820_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='last_notified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
