# Generated by Django 2.2.1 on 2020-10-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0133_errorlog_last_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='aws_url',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegramgroup',
            name='aws_profile_pic_url',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
