# Generated by Django 2.2.1 on 2020-10-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0134_auto_20201006_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='slptoken',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
