# Generated by Django 2.2.1 on 2020-11-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0139_slptoken_faucet_telegram_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='slptoken',
            name='faucet_period_hours',
            field=models.IntegerField(default=24),
        ),
    ]
