# Generated by Django 2.2.1 on 2021-03-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0142_auto_20201227_0441'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_activity'], name='main_user_last_ac_db96ea_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['frozen'], name='main_user_frozen_d1ba65_idx'),
        ),
    ]
