# Generated by Django 2.2.1 on 2021-03-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0143_auto_20210306_0511'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['tip_amount'], name='main_conten_tip_amo_d076b0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_hash'], name='main_transa_transac_77a9ca_idx'),
        ),
    ]
