# Generated by Django 2.2.1 on 2021-04-06 07:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0145_slptoken_verbose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slptoken',
            name='verbose',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
