# Generated by Django 2.2.1 on 2021-04-06 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0146_auto_20210406_0744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slptoken',
            old_name='verbose',
            new_name='verbose_names',
        ),
    ]
