# Generated by Django 2.2.1 on 2021-04-08 05:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0147_auto_20210406_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='slptoken',
            name='date_delisted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
