# Generated by Django 2.2.1 on 2021-04-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0148_slptoken_date_delisted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slptoken',
            name='date_delisted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
