# Generated by Django 2.2.1 on 2021-04-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0150_slptoken_announce_delisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='withdraw_all',
            field=models.BooleanField(default=False),
        ),
    ]
