# Generated by Django 2.2.1 on 2021-04-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0151_withdrawal_withdraw_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='rain',
            name='message_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
