# Generated by Django 2.2.1 on 2021-04-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0152_rain_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rain',
            name='message_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
