# Generated by Django 2.2.1 on 2021-06-12 00:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0152_rain_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastGroupActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_group_activities', to='main.TelegramGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_group_activities', to='main.User')),
            ],
            options={
                'unique_together': {('group', 'user')},
            },
        ),
    ]
