# Generated by Django 2.2.1 on 2021-06-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0152_rain_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='slptoken',
            name='max_bet_for_sphere',
            field=models.FloatField(default=10000),
        ),
        migrations.AddField(
            model_name='slptoken',
            name='min_bet_for_sphere',
            field=models.FloatField(default=50),
        ),
    ]
