# Generated by Django 2.2.1 on 2021-06-12 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0153_auto_20210429_0907'),
        ('main', '0153_lastgroupactivity'),
    ]

    operations = [
    ]
