# Generated by Django 2.2.1 on 2021-06-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0153_lastgroupactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='slptoken',
            name='sphere_manager',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
