# Generated by Django 2.2.1 on 2021-06-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0154_slptoken_sphere_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='slptoken',
            name='sphere_percentage_fee',
            field=models.FloatField(default=0.0),
        ),
    ]
