
# Generated by Django 2.2.1 on 2021-06-29 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0153_auto_20210608_0600'),
        ('main', '0155_slptoken_sphere_percentage_fee'),
        ('main', '0154_slptoken_sphere_manager'),
    ]

    operations = [
    ]