# Generated by Django 2.2.1 on 2021-06-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0156_merge_20210629_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rain',
            name='message_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]