# Generated by Django 2.2.1 on 2021-07-14 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0157_auto_20210629_0831'),
        ('main', '0153_auto_20210429_0907'),
    ]

    operations = [
    ]
