# Generated by Django 2.2.1 on 2021-07-14 04:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0158_merge_20210714_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='slptoken',
            name='token_exchange',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='rain',
            name='message_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
