# Generated by Django 2.2.1 on 2021-07-15 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0159_auto_20210714_0443'),
        ('main', '0154_merge_20210612_0034'),
    ]

    operations = [
    ]