# Generated by Django 2.2.1 on 2021-08-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0160_merge_20210715_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribed_to_watchtower',
            field=models.BooleanField(default=False),
        ),
    ]
