# Generated by Django 2.2.1 on 2021-10-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0161_user_subscribed_to_watchtower'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='date_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
