# Generated by Django 2.2.1 on 2021-11-03 23:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0162_withdrawal_date_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slptoken',
            name='token_exchange',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
