# Generated by Django 2.2.1 on 2021-06-02 07:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0152_rain_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_bet', models.FloatField(default=0)),
                ('min_bet', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=200)),
                ('group_username', models.CharField(max_length=200)),
                ('message_id', models.CharField(max_length=100)),
                ('challenger_id', models.CharField(blank=True, max_length=50, null=True)),
                ('challenger_username', models.CharField(blank=True, max_length=50, null=True)),
                ('contender_id', models.CharField(blank=True, max_length=50, null=True)),
                ('contender_username', models.CharField(blank=True, max_length=50, null=True)),
                ('bet_amount', models.FloatField(default=0)),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('vacant', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('cancelled_by', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('scenario', models.IntegerField(default=1)),
                ('slptoken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='main.SLPToken')),
            ],
        ),
    ]
