# Generated by Django 2.2.1 on 2021-06-03 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sphere', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='scenario',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='vacant',
        ),
    ]
