# Generated by Django 2.2.1 on 2021-06-08 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sphere', '0002_auto_20210603_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='group_username',
        ),
    ]
