# Generated by Django 2.2.1 on 2021-06-08 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sphere', '0003_auto_20210608_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='slptoken',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sphere_challenges', to='main.SLPToken'),
        ),
    ]
