# Generated by Django 2.2.1 on 2021-06-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphere', '0005_auto_20210608_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challenger_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='contender_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
