# Generated by Django 2.2.1 on 2021-06-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphere', '0006_auto_20210609_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='manager',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
