# Generated by Django 2.2.1 on 2021-06-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphere', '0007_auto_20210616_0803'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setup',
        ),
        migrations.AddField(
            model_name='challenge',
            name='percentage_fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='challenge',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slptoken',
            name='emoji',
            field=models.CharField(default='💰', max_length=10),
        ),
    ]
