# Generated by Django 2.2.1 on 2021-06-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphere', '0008_auto_20210617_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='chat_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
