# Generated by Django 2.2.1 on 2021-07-14 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sphere', '0009_challenge_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_id', models.CharField(max_length=100)),
                ('seller_id', models.CharField(max_length=50)),
                ('orb_amount', models.FloatField(default=0.0)),
                ('spice_amount', models.FloatField(default=0.0)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_processed', models.DateTimeField(null=True)),
            ],
        ),
    ]
