# Generated by Django 2.2.1 on 2021-07-15 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sphere', '0010_exchange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='orb_amount',
            new_name='exchange_amount',
        ),
        migrations.RenameField(
            model_name='exchange',
            old_name='spice_amount',
            new_name='payment_amount',
        ),
        migrations.AddField(
            model_name='exchange',
            name='exchange_token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange', to='sphere.SLPToken'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='payment_token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='sphere.SLPToken'),
        ),
    ]
